export const HC_PRODUCTS = [
  {
    id: "hc-men-jacket-1",
    name: "Urban Black Jacket",
    gender: "men",
    category: "jacket",
    price: 2799,
    image: "HCimages/jacket1.jpg",
    description: "Street-ready water-resistant shell with HIGHCLASS fit.",
  },
  {
    id: "hc-men-jacket-3",
    name: "Lether BrownJacket",
    gender: "men",
    category: "jacket",
    price: 6799,
    image: "HCimages/jacket3.jpg",
    description: "Street-ready water-resistant shell with HIGHCLASS fit.",
  },
  {
    id: "hc-men-jacket-4",
    name: " Stylish Urban Black Jacket",
    gender: "men",
    category: "jacket",
    price: 12799,
    image: "HCimages/jacket4.jpg",
    description: "Street-ready water-resistant shell with HIGHCLASS fit.",
  },
  {
    id: "hc-men-jacket-5",
    name: "Denim Black Jacket",
    gender: "men",
    category: "jacket",
    price: 15799,
    image: "HCimages/jacket5.jpg",
    description: "Street-ready water-resistant shell with HIGHCLASS fit.",
  },
{
    id: "hc-men-jacket-6",
    name: "Urban Black Lether Jacket",
    gender: "men",
    category: "jacket",
    price: 12799,
    image: "HCimages/jacket6.jpg",
    description: "Street-ready water-resistant shell with HIGHCLASS fit.",
  },
  {
    id: "hc-women-jacket-1",
    name: "Urban Grey Jacket",
    gender: "women",
    category: "jacket",
    price: 6799,
    image: "HCimages/jacket8.jpg",
    description: "Street-ready water-resistant shell with HIGHCLASS fit.",
  },
  {
    id: "hc-women-jacket-2",
    name: "Urban Milky Cream Jacket",
    gender: "women",
    category: "jacket",
    price: 11799,
    image: "HCimages/jacket9.jpg",
    description: "Street-ready water-resistant shell with HIGHCLASS fit.",
  },
  {
    id: "hc-women-jacket-3",
    name: "Urban Tan Jacket",
    gender: "women",
    category: "jacket",
    price: 10799,
    image: "HCimages/jacket10.jpg",
    description: "Street-ready water-resistant shell with HIGHCLASS fit.",
  },

  {
    id: "hc-men-jacket-7",
    name: "Stylish Denim Jacket",
    gender: "men",
    category: "jacket",
    price: 12799,
    image: "HCimages/jacket11.jpg",
    description: "Street-ready water-resistant shell with HIGHCLASS fit.",
  },
  {
    id: "hc-women-lehenga-1",
    name: "Wedding lehenga",
    gender: "women",
    category: "lehenga",
    price: 80499,
    image: "HCimages/lehenga3.jpg",
    description: "Flowy wedding lehenga with subtle shine.",
  },
  {
    id: "hc-women-lehenga-2",
    name: "Scarlet lehenga",
    gender: "women",
    category: "lehenga",
    price: 73499,
    image: "HCimages/lehenga4.jpg",
    description: "Flowy wedding lehenga with subtle shine.",
  },
  {
    id: "hc-women-lehenga-3",
    name: "Choclate lehenga",
    gender: "women",
    category: "lehenga",
    price: 54499,
    image: "HCimages/lehenga5.jpg",
    description: "Flowy wedding lehenga with subtle shine.",
  },
  {
    id: "hc-women-lehenga-4",
    name: "Scarlet lehenga",
    gender: "women",
    category: "lehenga",
    price: 94499,
    image: "HCimages/lehenga6.jpg",
    description: "Flowy wedding lehenga with subtle shine.",
  },
  {
    id: "hc-women-lehenga-5",
    name: "Bloody Red lehenga",
    gender: "women",
    category: "lehenga",
    price: 67499,
    image: "HCimages/lehnga1.jpg",
    description: "Flowy wedding lehenga with subtle shine.",
  },
  {
    id: "hc-women-lehenga-6",
    name: "Black Diamond lehenga",
    gender: "women",
    category: "lehenga",
    price: 67499,
    image: "HCimages/lehnga2.jpg",
    description: "Flowy wedding lehenga with subtle shine.",
  },
  {
    id: "hc-women-gown-1",
    name: "Sunshine Gown",
    gender: "women",
    category: "gown",
    price: 7499,
    image: "HCimages/gown5.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-gown-2",
    name: "Galaxy Gown",
    gender: "women",
    category: "gown",
    price: 14499,
    image: "HCimages/gown6.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-gown-3",
    name: "Pearl Gown",
    gender: "women",
    category: "gown",
    price: 9499,
    image: "HCimages/gown7.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-gown-4",
    name: "Krimson Gown",
    gender: "women",
    category: "gown",
    price: 24499,
    image: "HCimages/gown8.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-gown-5",
    name: "Jasper Gown",
    gender: "women",
    category: "gown",
    price: 24499,
    image: "HCimages/gown9.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-gown-6",
    name: "Strawberry Gown",
    gender: "women",
    category: "gown",
    price: 22499,
    image: "HCimages/gown10.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-gown-7",
    name: "Blood Red Gown",
    gender: "women",
    category: "gown",
    price: 37499,
    image: "HCimages/gown11.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-gown-8",
    name: "Soul Gown",
    gender: "women",
    category: "gown",
    price: 74499,
    image: "HCimages/gown12.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-gown-9",
    name: "White Rose Gown",
    gender: "women",
    category: "gown",
    price: 62499,
    image: "HCimages/gown13.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-gown-10",
    name: "Moon Night  Gown",
    gender: "women",
    category: "gown",
    price: 68499,
    image: "HCimages/gown14.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-1",
    name: "Soul light saree",
    gender: "women",
    category: "saree",
    price: 4499,
    image: "HCimages/saree1.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-2",
    name: "Krimson light saree",
    gender: "women",
    category: "saree",
    price: 6499,
    image: "HCimages/saree2.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-3",
    name: "Pearl White saree",
    gender: "women",
    category: "saree",
    price: 3499,
    image: "HCimages/saree3.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-4",
    name: "Sea Sour Light saree",
    gender: "women",
    category: "saree",
    price: 8499,
    image: "HCimages/saree4.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-5",
    name: "Scarlet Red saree",
    gender: "women",
    category: "saree",
    price: 8499,
    image: "HCimages/saree5.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-6",
    name: "Golden Red saree",
    gender: "women",
    category: "saree",
    price: 14499,
    image: "HCimages/saree6.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-7",
    name: "Red Wine  saree",
    gender: "women",
    category: "saree",
    price: 10499,
    image: "HCimages/saree7.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-8",
    name: "Red Moon saree",
    gender: "women",
    category: "saree",
    price: 8499,
    image: "HCimages/saree8.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-9",
    name: "Red Shine  saree",
    gender: "women",
    category: "saree",
    price: 16499,
    image: "HCimages/saree9.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-saree-10",
    name: "Soul white saree",
    gender: "women",
    category: "saree",
    price: 24499,
    image: "HCimages/saree10.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-salwar-1",
    name: "Red Wine salwar",
    gender: "women",
    category: "salwar",
    price: 12499,
    image: "HCimages/salwar1.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
{
    id: "hc-women-salwar-2",
    name: "Blue Sky salwar",
    gender: "women",
    category: "salwar",
    price: 14499,
    image: "HCimages/salwar2.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-salwar-3",
    name: "Golden Shine  salwar",
    gender: "women",
    category: "salwar",
    price: 13499,
    image: "HCimages/salwar3.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-salwar-4",
    name: "Day Rise salwar",
    gender: "women",
    category: "salwar",
    price: 16499,
    image: "HCimages/salwar4.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-salwar-5",
    name: "Day Top salwar",
    gender: "women",
    category: "salwar",
    price: 22499,
    image: "HCimages/salwar5.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-women-salwar-6",
    name: "Blue sky salwar",
    gender: "women",
    category: "salwar",
    price: 17499,
    image: "HCimages/salwar6.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-men-shirts&pants-1",
    name: "Brown - White shirt & pant",
    gender: "men",
    category: "shirts-pants",
    price: 1499,
    image: "HCimages/shirt-pant.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
{
    id: "hc-men-shirts&pants-2",
    name: "Brown - Black shirt & pant",
    gender: "men",
    category: "shirts-pants",
    price: 1699,
    image: "HCimages/shirt-pant2.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-men-shirts&pants-3",
    name: "All Black shirt & pant",
    gender: "men",
    category: "shirts-pants",
    price: 2499,
    image: "HCimages/shirt-pant3.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-men-shirts&pants-4",
    name: "Premium T-shirts",
    gender: "men",
    category: "shirts-pants",
    price: 1499,
    image: "HCimages/shirt-pant4.jpg",
    description: "Flowy evening gown with subtle shine.",
  },
  {
    id: "hc-men-shirts&pants-5",
    name: "Navy - White shirt & pant",
    gender: "men",
    category: "shirts-pants",
    price: 1499,
    image: "HCimages/shirt-pant5.jpg",
    description: "Flowy evening gown with subtle shine.",
  },



















  // ...baaki saree, salwar, lehenga, shirt-pant, etc
];
